# Syntax Directive
# syntax=docker/dockerfile:1.7-labs

# Stage 1: Build Image
FROM node:22-alpine as node_uv_build

RUN apk add --no-cache python3 py3-pip curl

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.cargo/bin:${PATH}"

RUN node --version && npx --version && uv --version

# Stage 2: Runtime Base Image
FROM node:22-alpine

RUN apk add --no-cache 

COPY --from=node_uv_build /root/.cargo/bin/uv /usr/local/bin/uv

WORKDIR /app

CMD ["node"]
